name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Lint JavaScript files
        run: npm run lint

      - name: Lint TypeScript declaration files
        run: npm run lint:dts

      - name: Run tests
        run: npm run test:ci

      - name: Run module tests
        run: npm run test:esm

      - name: Run integration tests
        run: npm run test:integration

      - name: Run benchmark
        run: npm run benchmark

      - name: Codecov
        uses: codecov/codecov-action@v3
